title: Srinivas Yalagam
logo: /assets/img/logo.png
description: Implementing Computer Vision and Machine Learning Algorithms for ADAS and Autonomous Driving
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
Projects: https://github.com/yalagamsrinivas?tab=repositories
